### PR TITLE
contribution-to-development/fix

### PR DESCRIPTION
**Pull request by teqsk1514**
Fix for [ISSUE: #673](https://github.com/TobikoData/sqlmesh/issues/673)

### CODE REVIEW

**Comment by tobymao** [comment]
can you just fix the documentation instead of the male file?

**Comment by teqsk1514** [comment]
Sure @tobymao .

**Comment by teqsk1514** [comment]
Done @tobymao, I created lots of commits for this small change. Could you let me know if it is unnecessary so I can close this PR and create a fresh one?

**Review by tobymao — APPROVED** [review]
it’s fine thanks!

**Comment by teqsk1514** [comment]
Hi, @tobymao, the solution is not yet reflected in the [documentation](https://sqlmesh.readthedocs.io/en/stable/development/#commands-reference). Did I miss adding anything?

**Comment by tobymao** [comment]
it should be reflected in the latest docs, stable requires a release

**Comment by teqsk1514** [comment]
Ok 👍

**Pull request merged**
