### PR TITLE
Fix: Return no missing intervals for seed models if evaluated at least once

### PR DESCRIPTION
**Pull request by izeigerman**

### CODE REVIEW

**Review by tobymao — APPROVED** [review]

**Review by eakmanrq — COMMENTED** [review]
Do we allow hooks on seeds? If we do, wouldn't that then mean that hooks only run once? I thought we tracked intervals for everything, even if they are effectively no-ops, in order to ensure that hooks are run.

**Comment by tobymao** [comment]
we probably don’t need hooks for seeds

**Comment by izeigerman** [comment]
@eakmanrq @tobymao  Even if we do allow hooks for seeds I think the contract is that hooks should run on each **evaluation**. I think it's pretty clear that seeds are evaluated once and only once (unlike full model kind), so there should be no problem with that.

**Comment by eakmanrq** [comment]
@izeigerman What is our reasoning then why views would then be evaluated on each cadence? I remember when we discussed this we decided to that because someone might have hooks on the views that they would want to be executed. I just don't see why this is any different than seeds? I think consistency here would be great.

**Comment by izeigerman** [comment]
@eakmanrq 

> because someone might have hooks on the views that they would want to be executed

That's not the only reason though. View might be dependent on something like `@latest_ds`, so the evaluation won't be the same every time.

**Comment by eakmanrq** [comment]
Fair but someone might also do other things with hooks on views that have a static definition (just like their seeds). It seems non-intuitive to allow that but not allow that on seeds.

**Comment by tobymao** [comment]
fwiw i think views of seeds are different so i'm fine with it

**Pull request merged**
