### PR TITLE
Feat: A CLI command to print the name of the physical table for a model

### PR DESCRIPTION
**Pull request by izeigerman**
Adding a new CLI command to help figure out the name of the physical table given a model name. The local model snapshot is used for this purpose.

### CODE REVIEW

**Comment by tobymao** [comment]
can you add notebook?

**Comment by izeigerman** [comment]
@tobymao what's the use case for it? Can't notebook call the context method directly?

**Comment by tobymao** [comment]
we try to mimic all cli commands as magics, do we want to change that?

**Comment by izeigerman** [comment]
@tobymao added the magic

**Comment by eakmanrq** [comment]
@izeigerman Can you also add tests for both CLI and magics? 

https://github.com/TobikoData/sqlmesh/blob/2fd6721594dc3f7dc2cfafe57384d23943d8817b/tests/cli/test_cli.py
https://github.com/TobikoData/sqlmesh/blob/2fd6721594dc3f7dc2cfafe57384d23943d8817b/tests/integrations/jupyter/test_magics.py

**Comment by izeigerman** [comment]
@eakmanrq added tests, thanks

**Review by tobymao — APPROVED** [review]

**Pull request merged**
