### PR TITLE
Fix: Support of the table renaming in Snowflake and Databricks

### PR DESCRIPTION
**Pull request by izeigerman**

### CODE REVIEW

**Review by georgesittas — APPROVED** [review]
Perhaps this is something that we can fix upstream in sqlglot?

**Comment by tobymao** [comment]
this is already fixed in sqlglot isn't it?

**Comment by georgesittas** [comment]
I think we only drop the db, ie. the other way around: https://github.com/tobymao/sqlglot/blob/fb9a7ad8f2af98a248e4576677b7b615b9d4c3e7/sqlglot/generator.py#L2970-L2974

**Comment by tobymao** [comment]
ah, let's fix it there then

**Pull request merged**
