### PR TITLE
Fix: mysql does not support FULL OUTER JOIN

### PR DESCRIPTION
**Pull request by treysp**
Update sushi model customer_revenue_lifetime.sql to use `LEFT JOIN`/`UNION`/`RIGHT JOIN` instead of `FULL OUTER JOIN` so it can run on mysql

### CODE REVIEW

**Comment by tobymao** [comment]
i think this can just be a sqlglot transpilation cc @GeorgeSittas and @eakmanrq 

what do you think?

full join into left right union

**Comment by tobymao** [comment]
let me see how easy this

**Comment by eakmanrq** [comment]
Yeah handling this in transpilation would be ideal.

**Comment by GeorgeSittas** [comment]
+1, seems like a good improvement for sqlglot

**Pull request closed without merging**
