### PR TITLE
chore: remove fallback values

### PR DESCRIPTION
**Pull request by eakmanrq**

### CODE REVIEW

**Comment by tobymao** [comment]
what's the motivation for this change?

**Comment by eakmanrq** [comment]
Just cleanup. Ran into it in default catalog PR and wanted to split it out since it is a standalone change.

**Comment by izeigerman** [comment]
I added the fallbacks. Not sure why do we need to fail instead

**Comment by eakmanrq** [comment]
@izeigerman This should never happen right? I figure if we did end up in a situation where we would use these fallbacks that we would prefer to error instead.

**Comment by izeigerman** [comment]
@eakmanrq sorry for the delayed reply. I noticed that in some cases in the past (maybe not right now) we called these property methods (`_dag`, `_snapshot_mapping`) recursively while computing the `__dag` and `__snapshot_mapping` values. I see why shouldn't we fallback to defaults in this case

**Pull request closed without merging**
